/**
 * Redux action-types for the project, Check-In.
 *
 * @author Michael David Gill <michaelgill1969@gmail.com>
 * @license
 * Copyright 2019 Cryonics Institute
 *
 * This file is part of Check-In.
 *
 * Check-In is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * Check-In is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Check-In.  If not, see <https://www.gnu.org/licenses/>.
 */

export const ADD_DOCUMENT_REQUESTED = 'ADD_DOCUMENT_REQUESTED'
export const ADD_DOCUMENT_REJECTED = 'ADD_DOCUMENT_REJECTED'
export const ADD_DOCUMENT_FULFILLED = 'ADD_DOCUMENT_FULFILLED'
export const ADD_BUDDY_REQUESTED = 'ADD_BUDDY_REQUESTED'
export const ADD_BUDDY_REJECTED = 'ADD_BUDDY_REJECTED'
export const ADD_BUDDY_FULFILLED = 'ADD_BUDDY_FULFILLED'
export const CHECKIN_REQUESTED = 'CHECKIN_REQUESTED'
export const CHECKIN_REJECTED = 'CHECKIN_REJECTED'
export const CHECKIN_FULFILLED = 'CHECKIN_FULFILLED'
export const GET_DOCUMENT_REQUESTED = 'GET_DOCUMENT_REQUESTED'
export const GET_DOCUMENT_REJECTED = 'GET_DOCUMENT_REJECTED'
export const GET_DOCUMENT_FULFILLED = 'GET_DOCUMENT_FULFILLED'
export const HIDE_TIP_REQUESTED = 'HIDE_TIP_REQUESTED'
export const HIDE_TIP_REJECTED = 'HIDE_TIP_REJECTED'
export const HIDE_TIP_FULFILLED = 'HIDE_TIP_FULFILLED'
export const INITIALIZE_STORE_REQUESTED = 'INITIALIZE_STORE_REQUESTED'
export const INITIALIZE_STORE_REJECTED = 'INITIALIZE_STORE_REJECTED'
export const INITIALIZE_STORE_FULFILLED = 'INITIALIZE_STORE_FULFILLED'
export const MUTATE_INPUTS_REQUESTED = 'MUTATE_INPUTS_REQUESTED'
export const MUTATE_INPUTS_REJECTED = 'MUTATE_INPUTS_REJECTED'
export const MUTATE_INPUTS_FULFILLED = 'MUTATE_INPUTS_FULFILLED'
export const REGISTRATION_REQUESTED = 'REGISTRATION_REQUESTED'
export const REGISTRATION_REJECTED = 'REGISTRATION_REJECTED'
export const REGISTRATION_FULFILLED = 'REGISTRATION_FULFILLED'
export const REMOVE_INPUTS_REQUESTED = 'REMOVE_INPUTS_REQUESTED'
export const REMOVE_INPUTS_REJECTED = 'REMOVE_INPUTS_REJECTED'
export const REMOVE_INPUTS_FULFILLED = 'REMOVE_INPUTS_FULFILLED'
export const REMOVE_LISTENERS_REQUESTED = 'REMOVE_LISTENERS_REQUESTED'
export const REMOVE_LISTENERS_REJECTED = 'REMOVE_LISTENERS_REJECTED'
export const REMOVE_LISTENERS_FULFILLED = 'REMOVE_LISTENERS_FULFILLED'
export const REMOVE_TIMERS_REQUESTED = 'REMOVE_TIMERS_REQUESTED'
export const REMOVE_TIMERS_REJECTED = 'REMOVE_TIMERS_REJECTED'
export const REMOVE_TIMERS_FULFILLED = 'REMOVE_TIMERS_FULFILLED'
export const SET_LAST_ALERT_TIME = 'SET_LAST_ALERT_TIME'
export const SET_INPUT_PARAMETERS_REQUESTED = 'SET_INPUT_PARAMETERS_REQUESTED'
export const SET_INPUT_PARAMETERS_REJECTED = 'SET_INPUT_PARAMETERS_REJECTED'
export const SET_INPUT_PARAMETERS_FULFILLED = 'SET_INPUT_PARAMETERS_FULFILLED'
export const SET_LISTENER_INTERVAL_REQUESTED = 'SET_LISTENER_INTERVAL_REQUESTED'
export const SET_LISTENER_INTERVAL_REJECTED = 'SET_LISTENER_INTERVAL_REJECTED'
export const SET_TIMER_INTERVAL_FULFILLED = 'SET_TIMER_INTERVAL_FULFILLED'
export const SET_LISTENER_REQUESTED = 'SET_LISTENER_REQUESTED'
export const SET_LISTENER_REJECTED = 'SET_LISTENER_REJECTED'
export const SET_LISTENER_FULFILLED = 'SET_LISTENER_FULFILLED'
export const SET_TIMER_INTERVAL_REQUESTED = 'SET_TIMER_INTERVAL_REQUESTED'
export const SET_TIMER_INTERVAL_REJECTED = 'SET_TIMER_INTERVAL_REJECTED'
export const SET_LISTENER_INTERVAL_FULFILLED = 'SET_LISTENER_INTERVAL_FULFILLED'
export const SET_SHORTEST_INTERVAL_REQUESTED = 'SET_SHORTEST_INTERVAL_REQUESTED'
export const SET_SHORTEST_INTERVAL_REJECTED = 'SET_SHORTEST_INTERVAL_REJECTED'
export const SET_SHORTEST_INTERVAL_FULFILLED = 'SET_SHORTEST_INTERVAL_FULFILLED'
export const SET_SNOOZE_REQUESTED = 'SET_SNOOZE_REQUESTED'
export const SET_SNOOZE_REJECTED = 'SET_SNOOZE_REJECTED'
export const SET_SNOOZE_FULFILLED = 'SET_SNOOZE_FULFILLED'
export const SET_TIMER_REQUESTED = 'SET_TIMER_REQUESTED'
export const SET_TIMER_REJECTED = 'SET_TIMER_REJECTED'
export const SET_TIMER_FULFILLED = 'SET_TIMER_FULFILLED'
export const SIGNIN_REQUESTED = 'SIGNIN_REQUESTED'
export const SIGNIN_REJECTED = 'SIGNIN_REJECTED'
export const SIGNIN_FULFILLED = 'SIGNIN_FULFILLED'
export const SIGNOUT_REQUESTED = 'SIGNOUT_REQUESTED'
export const SIGNOUT_REJECTED = 'SIGNOUT_REJECTED'
export const SIGNOUT_FULFILLED = 'SIGNOUT_FULFILLED'
