/**
 * Redux action-types for the project, Cryonics Check-In.
 *
 * @author Michael David Gill <michaelgill1969@gmail.com>
 * @license
 * Copyright 2019 Cryonics Institute
 *
 * This file is part of Cryonics Check-In.
 *
 * Cryonics Check-In is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * Cryonics Check-In is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * Cryonics Check-In.  If not, see <https://www.gnu.org/licenses/>.
 */

export const ADD_DOCUMENT_REQUESTED = 'ADD_DOCUMENT_REQUESTED'
export const ADD_DOCUMENT_REJECTED = 'ADD_DOCUMENT_REJECTED'
export const ADD_DOCUMENT_FULFILLED = 'ADD_DOCUMENT_FULFILLED'
export const ADD_PATIENT_REQUESTED = 'ADD_PATIENT_REQUESTED'
export const ADD_PATIENT_REJECTED = 'ADD_PATIENT_REJECTED'
export const ADD_PATIENT_FULFILLED = 'ADD_PATIENT_FULFILLED'
export const CHECKIN_REQUESTED = 'CHECKIN_REQUESTED'
export const CHECKIN_REJECTED = 'CHECKIN_REJECTED'
export const CHECKIN_FULFILLED = 'CHECKIN_FULFILLED'
export const GET_DOCUMENT_REQUESTED = 'GET_DOCUMENT_REQUESTED'
export const GET_DOCUMENT_REJECTED = 'GET_DOCUMENT_REJECTED'
export const GET_DOCUMENT_FULFILLED = 'GET_DOCUMENT_FULFILLED'
export const FIND_CHECKIN_TIMES_REQUESTED = 'FIND_CHECKIN_TIMES_REQUESTED'
export const FIND_CHECKIN_TIMES_REJECTED = 'FIND_CHECKIN_TIMES_REJECTED'
export const FIND_CHECKIN_TIMES_FULFILLED = 'FIND_CHECKIN_TIMES_FULFILLED'
export const MUTATE_INPUTS_REQUESTED = 'MUTATE_INPUTS_REQUESTED'
export const MUTATE_INPUTS_REJECTED = 'MUTATE_INPUTS_REJECTED'
export const MUTATE_INPUTS_FULFILLED = 'MUTATE_INPUTS_FULFILLED'
export const REGISTRATION_REQUESTED = 'REGISTRATION_REQUESTED'
export const REGISTRATION_REJECTED = 'REGISTRATION_REJECTED'
export const REGISTRATION_FULFILLED = 'REGISTRATION_FULFILLED'
export const REMOVE_INPUTS_REQUESTED = 'REMOVE_INPUTS_REQUESTED'
export const REMOVE_INPUTS_REJECTED = 'REMOVE_INPUTS_REJECTED'
export const REMOVE_INPUTS_FULFILLED = 'REMOVE_INPUTS_FULFILLED'
export const REMOVE_LISTENER = 'REMOVE_LISTENER'
export const REMOVE_LISTENERS = 'REMOVE_LISTENERS'
export const REMOVE_TIMER = 'REMOVE_TIMER'
export const REMOVE_TIMERS = 'REMOVE_TIMERS'
export const SELECT_STATUS = 'SELECT_STATUS'
export const SET_ALERT_ACTIVE = 'SET_ALERT_ACTIVE'
export const SET_LAST_ALERT_TIME = 'SET_LAST_ALERT_TIME'
export const SET_LISTENER_INTERVAL_REQUESTED = 'SET_LISTENER_INTERVAL_REQUESTED'
export const SET_LISTENER_INTERVAL_REJECTED = 'SET_LISTENER_INTERVAL_REJECTED'
export const SET_TIMER_INTERVAL_FULFILLED = 'SET_TIMER_INTERVAL_FULFILLED'
export const SET_LISTENER_REQUESTED = 'SET_LISTENER_REQUESTED'
export const SET_LISTENER_REJECTED = 'SET_LISTENER_REJECTED'
export const SET_LISTENER_FULFILLED = 'SET_LISTENER_FULFILLED'
export const SET_TIMER_INTERVAL_REQUESTED = 'SET_TIMER_INTERVAL_REQUESTED'
export const SET_TIMER_INTERVAL_REJECTED = 'SET_TIMER_INTERVAL_REJECTED'
export const SET_LISTENER_INTERVAL_FULFILLED = 'SET_LISTENER_INTERVAL_FULFILLED'
export const SET_TIMER_REQUESTED = 'SET_TIMER_REQUESTED'
export const SET_TIMER_REJECTED = 'SET_TIMER_REJECTED'
export const SET_TIMER_FULFILLED = 'SET_TIMER_FULFILLED'
export const SIGNIN_REQUESTED = 'SIGNIN_REQUESTED'
export const SIGNIN_REJECTED = 'SIGNIN_REJECTED'
export const SIGNIN_FULFILLED = 'SIGNIN_FULFILLED'
export const SIGNOUT_REQUESTED = 'SIGNOUT_REQUESTED'
export const SIGNOUT_REJECTED = 'SIGNOUT_REJECTED'
export const SIGNOUT_FULFILLED = 'SIGNOUT_FULFILLED'
