// flow-typed signature: a4394a96f74cc49e52892baa2e3d11e3
// flow-typed version: <<STUB>>/redux-persist-sensitive-storage_v1.0.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist-sensitive-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist-sensitive-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'redux-persist-sensitive-storage/index' {
  declare module.exports: $Exports<'redux-persist-sensitive-storage'>;
}
declare module 'redux-persist-sensitive-storage/index.js' {
  declare module.exports: $Exports<'redux-persist-sensitive-storage'>;
}
