// flow-typed signature: 02db29d5edb1af2f7b078e7caef8c2f8
// flow-typed version: <<STUB>>/@react-native-community/async-storage_v1.12.0/flow_v0.125.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@react-native-community/async-storage'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@react-native-community/async-storage' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@react-native-community/async-storage/jest/async-storage-mock' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/lib/commonjs/AsyncStorage' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/lib/commonjs/AsyncStorage.native' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/lib/commonjs/hooks' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/lib/commonjs' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/lib/commonjs/RCTAsyncStorage.expo' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/lib/commonjs/RCTAsyncStorage' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/lib/module/AsyncStorage' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/lib/module/AsyncStorage.native' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/lib/module/hooks' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/lib/module' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/lib/module/RCTAsyncStorage.expo' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/lib/module/RCTAsyncStorage' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/src/AsyncStorage' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/src/AsyncStorage.native' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/src/hooks' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/src' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/src/RCTAsyncStorage.expo' {
  declare module.exports: any;
}

declare module '@react-native-community/async-storage/src/RCTAsyncStorage' {
  declare module.exports: any;
}

// Filename aliases
declare module '@react-native-community/async-storage/jest/async-storage-mock.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/jest/async-storage-mock'>;
}
declare module '@react-native-community/async-storage/lib/commonjs/AsyncStorage.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/commonjs/AsyncStorage'>;
}
declare module '@react-native-community/async-storage/lib/commonjs/AsyncStorage.native.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/commonjs/AsyncStorage.native'>;
}
declare module '@react-native-community/async-storage/lib/commonjs/hooks.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/commonjs/hooks'>;
}
declare module '@react-native-community/async-storage/lib/commonjs/index' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/commonjs'>;
}
declare module '@react-native-community/async-storage/lib/commonjs/index.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/commonjs'>;
}
declare module '@react-native-community/async-storage/lib/commonjs/RCTAsyncStorage.expo.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/commonjs/RCTAsyncStorage.expo'>;
}
declare module '@react-native-community/async-storage/lib/commonjs/RCTAsyncStorage.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/commonjs/RCTAsyncStorage'>;
}
declare module '@react-native-community/async-storage/lib/module/AsyncStorage.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/module/AsyncStorage'>;
}
declare module '@react-native-community/async-storage/lib/module/AsyncStorage.native.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/module/AsyncStorage.native'>;
}
declare module '@react-native-community/async-storage/lib/module/hooks.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/module/hooks'>;
}
declare module '@react-native-community/async-storage/lib/module/index' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/module'>;
}
declare module '@react-native-community/async-storage/lib/module/index.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/module'>;
}
declare module '@react-native-community/async-storage/lib/module/RCTAsyncStorage.expo.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/module/RCTAsyncStorage.expo'>;
}
declare module '@react-native-community/async-storage/lib/module/RCTAsyncStorage.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/lib/module/RCTAsyncStorage'>;
}
declare module '@react-native-community/async-storage/src/AsyncStorage.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/src/AsyncStorage'>;
}
declare module '@react-native-community/async-storage/src/AsyncStorage.native.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/src/AsyncStorage.native'>;
}
declare module '@react-native-community/async-storage/src/hooks.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/src/hooks'>;
}
declare module '@react-native-community/async-storage/src/index' {
  declare module.exports: $Exports<'@react-native-community/async-storage/src'>;
}
declare module '@react-native-community/async-storage/src/index.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/src'>;
}
declare module '@react-native-community/async-storage/src/RCTAsyncStorage.expo.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/src/RCTAsyncStorage.expo'>;
}
declare module '@react-native-community/async-storage/src/RCTAsyncStorage.js' {
  declare module.exports: $Exports<'@react-native-community/async-storage/src/RCTAsyncStorage'>;
}
